version: '2'

services:
    web:
        image: node:latest
        working_dir: /usr/src/app
        user: ${CURRENT_UID}
        ports: 
            - "3000:3000"
        volumes:
            - ./:/usr/src/app
        entrypoint: "./start.sh"
        environment: 
            MONGO_URI: "mongodb://root:example@mongo:27017/"
        links: 
            - mongo
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: test