version: "3"
services:
  distributor-db:
    image: mdillon/postgis:9.5
    container_name: distributor-db
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=distributor
    ports:
      - 5435:5432
    volumes:
      - distributor-postgres-data:/var/lib/postgresql/data

volumes:
   distributor-postgres-data:
      driver: local
