version: "3"
services:

  backend:
    build:
      context: backend
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - distributor-db
      - redis
    links:
      - distributor-db
      - redis
    env_file:
      - ./backend/.env
    environment: 
      - DISTRIBUTOR_DB_HOST=distributor-db
      - DISTRIBUTOR_DB_NAME=distributor
      - DISTRIBUTOR_DB_USER=master
      - DISTRIBUTOR_DB_PASSWORD=123456
      - DISTRIBUTOR_DB_PORT=5435
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379

  distributor-db:
    image: mdillon/postgis:9.5
    container_name: distributor-db
    hostname: distributor-db
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=distributor
    ports:
      - 5435:5432
    volumes:
      - distributor-postgres-data:/var/lib/postgresql/data

volumes:
  distributor-postgres-data:
    driver: local
