export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const SUCCESS_FETCH_CONTACTS = 'SUCCESS_FETCH_CONTACTS';
export const FAILURE_FETCH_CONTACTS = 'FAILURE_FETCH_CONTACTS';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SUCCESS_SEND_MESSAGE = 'SUCCESS_SEND_MESSAGE';
export const FAILURE_SEND_MESSAGE = 'FAILURE_SEND_MESSAGE';

export const INIT_CONTACT_FORM = 'INIT_CONTACT_FORM';