export const FETCH_DISTRICTS = 'FETCH_DISTRICTS';
export const SUCCESS_FETCH_DISTRICTS = 'SUCCESS_FETCH_DISTRICTS';
export const FAILURE_FETCH_DISTRICTS = 'FAILURE_FETCH_DISTRICTS';

export const FETCH_DISTRICT = 'FETCH_DISTRICT';
export const SUCCESS_FETCH_DISTRICT = 'SUCCESS_FETCH_DISTRICT';
export const FAILURE_FETCH_DISTRICT = 'FAILURE_FETCH_DISTRICT';
