export const FETCH_DISTRIBUTIONS = 'FETCH_DISTRIBUTIONS';
export const SUCCESS_FETCH_DISTRIBUTIONS = 'SUCCESS_FETCH_DISTRIBUTIONS';
export const FAILURE_FETCH_DISTRIBUTIONS = 'FAILURE_FETCH_DISTRIBUTIONS';
