export const FETCH_DONATIONS = 'FETCH_DONATIONS';
export const SUCCESS_FETCH_DONATIONS = 'SUCCESS_FETCH_DONATIONS';
export const FAILURE_FETCH_DONATIONS = 'FAILURE_FETCH_DONATIONS';

export const FETCH_DONATION = 'FETCH_DONATION';
export const SUCCESS_FETCH_DONATION = 'SUCCESS_FETCH_DONATION';
export const FAILURE_FETCH_DONATION = 'FAILURE_FETCH_DONATION';
