export const FETCH_HOSPITALS = 'FETCH_HOSPITALS';
export const SUCCESS_FETCH_HOSPITALS = 'SUCCESS_FETCH_HOSPITALS';
export const FAILURE_FETCH_HOSPITALS = 'FAILURE_FETCH_HOSPITALS';

export const FETCH_HOSPITAL = 'FETCH_HOSPITAL';
export const SUCCESS_FETCH_HOSPITAL = 'SUCCESS_FETCH_HOSPITAL';
export const FAILURE_FETCH_HOSPITAL = 'FAILURE_FETCH_HOSPITAL';
