export const FETCH_LOCALITIES = 'FETCH_LOCALITIES';
export const SUCCESS_FETCH_LOCALITIES = 'SUCCESS_FETCH_LOCALITIES';
export const FAILURE_FETCH_LOCALITIES = 'FAILURE_FETCH_LOCALITIES';

export const FETCH_LOCALITY = 'FETCH_LOCALITY';
export const SUCCESS_FETCH_LOCALITY = 'SUCCESS_FETCH_LOCALITY';
export const FAILURE_FETCH_LOCALITY = 'FAILURE_FETCH_LOCALITY';