export const FETCH_REGIONS = 'FETCH_REGIONS';
export const SUCCESS_FETCH_REGIONS = 'SUCCESS_FETCH_REGIONS';
export const FAILURE_FETCH_REGIONS = 'FAILURE_FETCH_REGIONS';

export const FETCH_REGION = 'FETCH_REGION';
export const SUCCESS_FETCH_REGION = 'SUCCESS_FETCH_REGION';
export const FAILURE_FETCH_REGION = 'FAILURE_FETCH_REGION';