# Generated by Django 3.0.4 on 2020-03-25 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price per piece (KGS)')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('created_by', models.ForeignKey(auto_created=True, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='need_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(auto_created=True, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='need_modified_by', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distributor.NeedType', verbose_name='Type')),
            ],
        ),
    ]
