# Generated by Django 3.0.4 on 2020-03-25 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name (liters, kg, etc.)')),
            ],
        ),
        migrations.RemoveField(
            model_name='need',
            name='type',
        ),
        migrations.DeleteModel(
            name='NeedType',
        ),
        migrations.AddField(
            model_name='need',
            name='measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='distributor.Measure', verbose_name='Measure (liters, kg, etc.)'),
        ),
    ]
