# Generated by Django 3.0.4 on 2020-03-25 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributor', '0003_auto_20200325_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator_type', models.CharField(choices=[('ORGANIZATION', 'ORGANIZATION'), ('PERSONAL', 'PERSONAL')], default='ORGANIZATION', max_length=12, verbose_name='Donator Type')),
                ('donator_name', models.CharField(max_length=200, verbose_name='Donator Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Donation Description')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Date')),
                ('created_at', models.DateTimeField(verbose_name='Created Date')),
                ('created_by', models.ForeignKey(auto_created=True, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='donation_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(auto_created=True, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='donation_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Amount')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distributor.Donation', verbose_name='Donation)')),
                ('need_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distributor.NeedType', verbose_name='Need Type')),
            ],
        ),
    ]
