# Generated by Django 3.0.4 on 2020-03-25 20:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_donation_donationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='To generate the map for your location', srid=4326)),
            ],
        ),
    ]
