# Generated by Django 3.0.4 on 2020-03-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0005_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='name_ky',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Name (liters, kg, etc.)'),
        ),
        migrations.AddField(
            model_name='measure',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Name (liters, kg, etc.)'),
        ),
    ]
