# Generated by Django 3.0.4 on 2020-03-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0007_auto_20200325_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='description_ky',
            field=models.TextField(max_length=1000, null=True, verbose_name='Donation Description'),
        ),
        migrations.AddField(
            model_name='donation',
            name='description_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Donation Description'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donator_name_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Donator Name'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donator_name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Donator Name'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
