# Generated by Django 3.0.4 on 2020-03-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0008_auto_20200325_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.CreateModel(
            name='HospitalPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distributor.Hospital', verbose_name='Hospital')),
            ],
        ),
    ]
