# Generated by Django 3.0.4 on 2020-03-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0011_auto_20200326_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_ky', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('actual', models.PositiveSmallIntegerField(verbose_name='Actual')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacity')),
                ('has_capacity', models.BooleanField(default=False, verbose_name='Has Capacity?')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='distributor.Hospital', verbose_name='Hospital')),
            ],
        ),
    ]
