# Generated by Django 3.0.4 on 2020-03-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0012_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capacity'),
        ),
    ]
