# Generated by Django 3.0.4 on 2020-03-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0013_auto_20200327_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Name')),
                ('name_ky', models.CharField(max_length=200, null=True, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Statistic Category',
                'verbose_name_plural': 'Statistic Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='needtype',
            options={'verbose_name': 'Need Type', 'verbose_name_plural': 'Need Types'},
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='statistic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.StatisticCategory', verbose_name='Category'),
        ),
    ]
