# Generated by Django 3.0.4 on 2020-03-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0015_add_statistic_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='actual',
            field=models.IntegerField(verbose_name='Actual'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacity'),
        ),
    ]
