# Generated by Django 3.0.4 on 2020-03-27 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0016_auto_20200327_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('hospital_name', models.CharField(max_length=250, verbose_name='Hospital Name')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Read Date')),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='distributor.Locality', verbose_name='Locality')),
            ],
        ),
    ]
