# Generated by Django 3.0.4 on 2020-03-30 16:17

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributor', '0021_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Пожертвование', 'verbose_name_plural': 'Пожертвования'},
        ),
        migrations.AlterModelOptions(
            name='donationdetail',
            options={'verbose_name': 'Детали пожертвования', 'verbose_name_plural': 'Детали пожертвований'},
        ),
        migrations.AlterModelOptions(
            name='helprequest',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Больница', 'verbose_name_plural': 'Больницы'},
        ),
        migrations.AlterModelOptions(
            name='hospitalneeds',
            options={'verbose_name': 'Потребность', 'verbose_name_plural': 'Потребности больниц'},
        ),
        migrations.AlterModelOptions(
            name='hospitalphonenumber',
            options={'verbose_name': 'Телефонный номер больницы', 'verbose_name_plural': 'Телефонные номера больниц'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Местность', 'verbose_name_plural': 'Местности'},
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерений'},
        ),
        migrations.AlterModelOptions(
            name='needtype',
            options={'verbose_name': 'Тип потребности', 'verbose_name_plural': 'Типы потребностей'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Область/город', 'verbose_name_plural': 'Области/города'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистики'},
        ),
        migrations.AlterModelOptions(
            name='statisticcategory',
            options={'verbose_name': 'Категория статистики', 'verbose_name_plural': 'Категории статистик'},
        ),
        migrations.RemoveField(
            model_name='needtype',
            name='price_per_piece',
        ),
        migrations.AddField(
            model_name='donationdetail',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена в сомах', max_digits=12, verbose_name='Цена за одну единицу (KGS)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='search_district_id',
            field=models.IntegerField(null=True, verbose_name='Search District ID'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='search_locality_id',
            field=models.IntegerField(null=True, verbose_name='Search Locality ID'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='search_region_id',
            field=models.IntegerField(null=True, verbose_name='Search Region ID'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(help_text='Введите название района', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_ky',
            field=models.CharField(help_text='Введите название района', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_ru',
            field=models.CharField(help_text='Введите название района', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(help_text='Выберите ранее созданный регион', on_delete=django.db.models.deletion.CASCADE, to='distributor.Region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='created_by',
            field=models.ForeignKey(auto_created=True, editable=False, help_text='Было создано пользователем', on_delete=django.db.models.deletion.PROTECT, related_name='donation_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Было создано'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(help_text='Введите описание пожертвования', max_length=1000, verbose_name='Описание пожертвования'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description_ky',
            field=models.TextField(help_text='Введите описание пожертвования', max_length=1000, null=True, verbose_name='Описание пожертвования'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description_ru',
            field=models.TextField(help_text='Введите описание пожертвования', max_length=1000, null=True, verbose_name='Описание пожертвования'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donator_name',
            field=models.CharField(help_text='Введите имя мецената', max_length=200, verbose_name='Имя мецената'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donator_name_ky',
            field=models.CharField(help_text='Введите имя мецената', max_length=200, null=True, verbose_name='Имя мецената'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donator_name_ru',
            field=models.CharField(help_text='Введите имя мецената', max_length=200, null=True, verbose_name='Имя мецената'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donator_type',
            field=models.CharField(choices=[('ORGANIZATION', 'ORGANIZATION'), ('PERSONAL', 'PERSONAL'), ('DONOR', 'DONOR')], default='ORGANIZATION', help_text='Выберите тип пожертвования', max_length=12, verbose_name='Тип пожертвования'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='modified_by',
            field=models.ForeignKey(auto_created=True, editable=False, help_text='Было изменено пользователем', on_delete=django.db.models.deletion.PROTECT, related_name='donation_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Было изменено'),
        ),
        migrations.AlterField(
            model_name='donationdetail',
            name='amount',
            field=models.PositiveIntegerField(help_text='Введите количество', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='donationdetail',
            name='donation',
            field=models.ForeignKey(help_text='Выберите ранее созданное пожертвование', on_delete=django.db.models.deletion.PROTECT, related_name='details', to='distributor.Donation', verbose_name='Пожертвование)'),
        ),
        migrations.AlterField(
            model_name='donationdetail',
            name='need_type',
            field=models.ForeignKey(help_text='Выберите тип нужды', on_delete=django.db.models.deletion.PROTECT, to='distributor.NeedType', verbose_name='Тип нужды'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='hospital_name',
            field=models.CharField(max_length=250, verbose_name='Наименование больницы'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='distributor.Locality', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='read_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(help_text='Введите адрес', max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='code',
            field=models.CharField(help_text='Введите код', max_length=50, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.Locality', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Для создания местоположения', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(help_text='Введите название больницы', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name_ky',
            field=models.CharField(help_text='Введите название больницы', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name_ru',
            field=models.CharField(help_text='Введите название больницы', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='hospitalneeds',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='hospitalneeds',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='needs', to='distributor.Hospital', verbose_name='Больница'),
        ),
        migrations.AlterField(
            model_name='hospitalneeds',
            name='need_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distributor.NeedType', verbose_name='Тип нужды'),
        ),
        migrations.AlterField(
            model_name='hospitalneeds',
            name='request_amount',
            field=models.IntegerField(verbose_name='Требуемое количество'),
        ),
        migrations.AlterField(
            model_name='hospitalneeds',
            name='reserve_amount',
            field=models.IntegerField(verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='hospitalphonenumber',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_numbers', to='distributor.Hospital', verbose_name='Больница'),
        ),
        migrations.AlterField(
            model_name='hospitalphonenumber',
            name='value',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть : 0555123456 или 03134 5 26 71 или 0312 45-26-71', regex='^[0]\\d{3,4}[- ]?\\d{1,2}[- ]?\\d{2}[- ]?\\d{2}$')], verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='district',
            field=models.ForeignKey(help_text='Выберите район', on_delete=django.db.models.deletion.CASCADE, to='distributor.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(help_text='Введите наименование', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name_ky',
            field=models.CharField(help_text='Введите наименование', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name_ru',
            field=models.CharField(help_text='Введите наименование', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=models.CharField(help_text='Введите наименование, например литр', max_length=200, unique=True, verbose_name='Наименование (литры, килограммы, и др.)'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name_ky',
            field=models.CharField(help_text='Введите наименование, например литр', max_length=200, null=True, unique=True, verbose_name='Наименование (литры, килограммы, и др.)'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name_ru',
            field=models.CharField(help_text='Введите наименование, например литр', max_length=200, null=True, unique=True, verbose_name='Наименование (литры, килограммы, и др.)'),
        ),
        migrations.AlterField(
            model_name='needtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='needtype',
            name='created_by',
            field=models.ForeignKey(auto_created=True, editable=False, help_text='Было создано пользователем', on_delete=django.db.models.deletion.PROTECT, related_name='needtype_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Было создано'),
        ),
        migrations.AlterField(
            model_name='needtype',
            name='measure',
            field=models.ForeignKey(help_text='Выберите единицу измерения', null=True, on_delete=django.db.models.deletion.PROTECT, to='distributor.Measure', verbose_name='Расширение'),
        ),
        migrations.AlterField(
            model_name='needtype',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='needtype',
            name='modified_by',
            field=models.ForeignKey(auto_created=True, editable=False, help_text='Было изменено пользователем', on_delete=django.db.models.deletion.PROTECT, related_name='needtype_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Было изменено'),
        ),
        migrations.AlterField(
            model_name='needtype',
            name='name',
            field=models.CharField(help_text='Введите наименование', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='needtype',
            name='name_ky',
            field=models.CharField(help_text='Введите наименование', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='needtype',
            name='name_ru',
            field=models.CharField(help_text='Введите наименование', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_ky',
            field=models.TextField(max_length=1000, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Введите название региона', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ky',
            field=models.CharField(help_text='Введите название региона', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ru',
            field=models.CharField(help_text='Введите название региона', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='actual',
            field=models.IntegerField(verbose_name='Текущий показатель'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Требуемое количество'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.StatisticCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='has_capacity',
            field=models.BooleanField(default=False, help_text='Отметьте галочкой чтобы показать поле', verbose_name='Показывать поле "Требуемое количество" '),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='distributor.Hospital', verbose_name='Больница'),
        ),
        migrations.AlterField(
            model_name='statisticcategory',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='statisticcategory',
            name='name_ky',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='statisticcategory',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Наименование'),
        ),
    ]
