# Generated by Django 3.0.4 on 2020-03-30 16:18


from django.db import migrations, models


def update_hospital_search_fields(apps, schema_editor):
    Hospital = apps.get_model('distributor', 'Hospital')
    hospitals = Hospital.objects.all()
    for hospital in hospitals:
        hospital.save()


class Migration(migrations.Migration):
    dependencies = [
        ('distributor', '0022_auto_20200330_1617'),
    ]

    operations = [
        migrations.RunPython(update_hospital_search_fields),
    ]
