# Generated by Django 3.0.4 on 2020-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0023_update_search_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationdetail',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Amount'),
        ),
    ]
