# Generated by Django 3.0.4 on 2020-03-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0024_auto_20200329_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needtype',
            name='price_per_piece',
        ),
        migrations.AddField(
            model_name='donationdetail',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Price per piece (KGS)'),
        ),
    ]
