# Generated by Django 3.0.4 on 2020-03-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0022_auto_20200328_1808'),
        ('distributor', '0025_auto_20200329_1531'),
    ]

    operations = [
    ]
