# Generated by Django 3.0.4 on 2020-03-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0026_merge_20200329_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationdetail',
            name='amount',
            field=models.PositiveIntegerField(help_text='Введите количество', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='donationdetail',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Цена в сомах', max_digits=12, verbose_name='Цена за одну единицу (KGS)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='actual',
            field=models.IntegerField(verbose_name='Текущий показатель'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Требуемое количество'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='has_capacity',
            field=models.BooleanField(default=False, help_text='Отметьте галочкой чтобы показать поле', verbose_name='Показывать поле "Требуемое количество" '),
        ),
    ]
