# Generated by Django 3.0.4 on 2020-03-31 14:56
from django.db import migrations, transaction

from distributor.models import Hospital
from distributor.models import Statistic
from distributor.models import StatisticCategory
from csv import reader
import os

def import_new_stuff(apps, schema_editor):
    with transaction.atomic():
        stat_cat = StatisticCategory.objects.get(name = 'Коек всего')

        with open(os.path.dirname(os.path.realpath(__file__)) + '/files/beds.csv', newline='') as file:
            csvin = reader(file, delimiter=',')
            for row in csvin:
                hospital_code = row[0]
                number_of_beds = row[1]
                try:
                    hospital = Hospital.objects.get(code=hospital_code)

                    stat_entry, created = Statistic.objects.get_or_create(hospital = hospital, category = stat_cat)
                    stat_entry.actual = number_of_beds
                    stat_entry.save()
                except:
                    raise Exception('Hospital not found ' + hospital_code)


class Migration(migrations.Migration):
    dependencies = [
        ('distributor', '0027_auto_20200330_1631'),
    ]

    operations = [
        migrations.RunPython(import_new_stuff),
    ]
