# Generated by Django 3.0.4 on 2020-03-31 19:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0028_import_new_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('text_ru', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('text_ky', models.CharField(max_length=300, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=200, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Электронный адрес')),
                ('title', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('body', models.TextField(max_length=400, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='ContactInfoPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть: 0555123456, 03134 5 26 71, 0312 45-26-71', regex='^[0]\\d{3,4}[- ]?\\d{1,2}[- ]?\\d{2}[- ]?\\d{2}$')], verbose_name='Телефонный номер')),
                ('is_whats_app', models.BooleanField(default=False, verbose_name='Вотсап номер?')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_numbers', to='distributor.ContactInfo', verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Телефонный номер',
                'verbose_name_plural': 'Телефонные номера',
            },
        ),
        migrations.CreateModel(
            name='ContactInfoEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.EmailField(max_length=100, verbose_name='Электронный адрес')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='distributor.ContactInfo', verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Электронный адрес',
                'verbose_name_plural': 'Электронные адреса',
            },
        ),
    ]
