# Generated by Django 3.0.4 on 2020-03-31 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

from distributor.models import ContactInfo


def create_contact_info(apps, schema_editor):
    contact_info = ContactInfo(text='По всем вопросам вы можете с нами связаться по телефонам',
                               text_ru='По всем вопросам вы можете с нами связаться по телефонам',
                               text_ky='По всем вопросам вы можете с нами связаться по телефонам')
    contact_info.save()


class Migration(migrations.Migration):
    dependencies = [
        ('distributor', '0029_contactinfo_contactinfoemail_contactinfophonenumber_contactmessage'),
    ]

    operations = [
        migrations.RunPython(create_contact_info),
    ]
