# Generated by Django 3.0.4 on 2020-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0038_add_hospital_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Скрыть больницу?', verbose_name='Скрыть'),
        ),
    ]
