# Generated by Django 3.0.4 on 2020-04-05 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0038_add_hospital_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(verbose_name='Кто выдал?')),
                ('receiver', models.TextField(verbose_name='Кто принял?')),
                ('date_of_distribute', models.DateField(verbose_name='Дата распределения')),
                ('status', models.CharField(choices=[('ready_to_sent', 'Подготовлено'), ('sent', 'Отправлено'), ('delivered', 'Доставлено')], max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donations', models.ManyToManyField(to='distributor.Donation', verbose_name='Пожертвования')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='distributor.Hospital')),
            ],
            options={
                'verbose_name': 'Запись для распределения',
                'verbose_name_plural': 'Распределения',
            },
        ),
    ]
