# Generated by Django 3.0.4 on 2020-04-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0039_hospital_hidden'),
        ('distributor', '0039_auto_20200418_1754'),
    ]

    operations = [
    ]
