# Generated by Django 3.0.4 on 2020-04-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0039_distribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ('-date_of_distribute',), 'verbose_name': 'Запись для распределения', 'verbose_name_plural': 'Распределения'},
        ),
    ]
