# Generated by Django 3.0.4 on 2020-04-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0040_auto_20200405_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='receiver',
            field=models.TextField(blank=True, verbose_name='Кто принял?'),
        ),
    ]
