# Generated by Django 3.0.4 on 2020-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0042_auto_20200405_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ('-distributed_at',), 'verbose_name': 'Запись для распределения', 'verbose_name_plural': 'Распределения'},
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='date_of_distribute',
            new_name='distributed_at',
        ),
        migrations.AddField(
            model_name='distribution',
            name='delivered_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
    ]
