# Generated by Django 3.0.4 on 2020-04-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0043_auto_20200405_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='donations',
        ),
        migrations.CreateModel(
            name='DistributionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Введите количество', verbose_name='Количество')),
                ('price_per_piece', models.DecimalField(decimal_places=2, help_text='Цена в сомах', max_digits=12, verbose_name='Цена за одну единицу (KGS)')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.Distribution')),
                ('donation', models.ForeignKey(help_text='Выберите ранее созданное пожертвование', on_delete=django.db.models.deletion.PROTECT, related_name='distribution_details', to='distributor.Donation', verbose_name='Пожертвование)')),
                ('need_type', models.ForeignKey(help_text='Выберите тип нужды', on_delete=django.db.models.deletion.PROTECT, to='distributor.NeedType', verbose_name='Тип нужды')),
            ],
            options={
                'verbose_name': 'Детали распределния',
                'verbose_name_plural': 'Детали распределений',
            },
        ),
    ]
