# Generated by Django 3.0.4 on 2020-04-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0045_auto_20200420_1856'),
        ('distributor', '0040_merge_20200419_1223'),
    ]

    operations = [
    ]
