# Generated by Django 3.0.4 on 2020-04-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0046_merge_20200420_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributiondetail',
            name='price_per_piece',
        ),
        migrations.AddField(
            model_name='distributiondetail',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена в сомах', max_digits=20, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Скрыть больницу?', verbose_name='Скрыто'),
        ),
    ]
