# Generated by Django 3.0.4 on 2020-04-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0047_auto_20200420_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributiondetail',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_detail', to='distributor.Distribution', verbose_name='Распределение'),
        ),
    ]
