# Generated by Django 3.0.4 on 2020-04-20 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributor', '0049_auto_20200420_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Скрыть больницу?', verbose_name='Скрыто'),
        ),
    ]
