# Generated by Django 3.0.4 on 2020-04-20 18:52
from django.db import migrations


def add_group(apps, schema_editor):
    permissions = [
        'add_hospital',
        'change_hospital',
        'view_hospital',
        'add_hospitalphonenumber',
        'change_hospitalphonenumber',
        'delete_hospitalphonenumber',
        'view_hospitalphonenumber',
        'add_hospitalneeds',
        'change_hospitalneeds',
        'delete_hospitalneeds',
        'view_hospitalneeds',
        'add_statistic',
        'change_statistic',
        'delete_statistic',
        'view_statistic',
    ]
    group, created = apps.get_model('auth', 'Group').objects.get_or_create(name="Hospital Managers")
    if created:
        print(f'{group} Group created')
        for permission in permissions:
            group.permissions.add(apps.get_model('auth', 'Permission').objects.get(codename=permission))
            print(f'Permitting {group} to {permission}')


class Migration(migrations.Migration):
    dependencies = [
        ('distributor', '0050_auto_20200420_1852'),
    ]

    operations = [
        migrations.RunPython(add_group)
    ]
