# Generated by Django 3.0.4 on 2020-04-20 18:52
from django.db import migrations
from django.contrib.auth.management import create_permissions


def add_group(apps, schema_editor):
    permissions = [
        'add_hospital',
        'change_hospital',
        'view_hospital',

        'add_hospitalphonenumber',
        'change_hospitalphonenumber',
        'delete_hospitalphonenumber',
        'view_hospitalphonenumber',

        'add_hospitalneeds',
        'change_hospitalneeds',
        'delete_hospitalneeds',
        'view_hospitalneeds',

        'add_statistic',
        'change_statistic',
        'delete_statistic',
        'view_statistic',

        'add_distributiondetail',
        'change_distributiondetail',
        'delete_distributiondetail',
        'view_distributiondetail',

        'add_distribution',
        'change_distribution',
        'delete_distribution',
        'view_distribution',
    ]

    # Костыль из https://stackoverflow.com/a/31735043/490502
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    group, created = apps.get_model('auth', 'Group').objects.get_or_create(name="Hospital Managers")
    if created:
        print(f'{group} Group created')
        for permission in permissions:
            group.permissions.add(apps.get_model('auth', 'Permission').objects.get(codename=permission))
            print(f'Permitting {group} to {permission}')


class Migration(migrations.Migration):
    dependencies = [
        ('distributor', '0050_auto_20200420_1852'),
    ]

    operations = [
        migrations.RunPython(add_group)
    ]
