# Generated by Django 3.0.4 on 2020-04-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0051_add_manager_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='В сомах', max_digits=20, null=True, verbose_name='Общая сумма пожертвования'),
        ),
        migrations.AlterField(
            model_name='donationdetail',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена в сомах', max_digits=20, null=True, verbose_name='Общая стоимость'),
        ),
    ]
