# Generated by Django 3.0.4 on 2020-04-23 06:26

from django.db import migrations, models, transaction
import django.db.models.deletion

def trunc_distributions(apps, schema_editor):
    with transaction.atomic():
        Distribution = apps.get_model('distributor', 'Distribution')
        Distribution.objects.all().delete()

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('distributor', '0052_auto_20200422_2007'),
    ]

    operations = [
        migrations.RunPython(trunc_distributions),
        migrations.AddField(
            model_name='distribution',
            name='donation',
            field=models.ForeignKey(help_text='Выберите ранее созданное пожертвование',
                                    on_delete=django.db.models.deletion.PROTECT, related_name='donation_details',
                                    to='distributor.Donation', verbose_name='Пожертвование)'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='distributiondetail',
            name='donation',
        ),
    ]
