# Generated by Django 3.0.4 on 2020-04-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0053_fix_distribution_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalneeds',
            options={'ordering': ['need_type__name'], 'verbose_name': 'Потребность', 'verbose_name_plural': 'Потребности больниц'},
        ),
        migrations.AddField(
            model_name='hospitalneeds',
            name='request_amount_month',
            field=models.IntegerField(default=0, verbose_name='Требуемое количество в месяц'),
            preserve_default=False,
        ),
    ]
