# Generated by Django 3.0.4 on 2020-03-27 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0017_helprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalphonenumber',
            name='value',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Phone number must be in these formats : 0555123456 or 03134 5 26 71 or 0312 45-26-71', regex='^[0]\\d{3,4}[- ]?\\d{1,2}[- ]?\\d{2}[- ]?\\d{2}$')], verbose_name='Phone Number'),
        ),
    ]
