name: telegram message
on: 
  push:
    branches: master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: -477706553
        token: 971718801:AAGhQD8eN6xG4R9u2leF4BVzfl6F26wqVLQ
        args: В мастер-ветку прилетел новый коммит ^_^
